# Minimal Home Assistant configuration for example tests

default_config:

# Enable REST API
api:

# Enable frontend
frontend:

# Enable system health
system_health:

timer:
  # Timer entity which is referenced by example tests
  test_timer:
    duration: '00:00:05'
