---
# Minimal Home Assistant configuration for example tests

default_config:

# Enable REST API
api:

# Enable frontend
frontend:

# Enable system health
system_health:

timer:
  # Timer entity which is referenced by example tests
  test_timer:
    duration: '00:00:05'

template:
  - triggers:
      - platform: time_pattern
        # Trigger every second to update the current datetime sensor
        seconds: "*"
    sensor:
      # Sensor to show current datetime for example test assertions
      - name: Current Datetime
        state: "{{ now().replace(microsecond=0).isoformat() }}"
